# Generated by Django 3.0.6 on 2025-06-24 18:20

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=55, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_be_deleted', models.BooleanField(default=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('return_days', models.CharField(default=0, max_length=50)),
                ('expected_delivery_days', models.CharField(default=0, max_length=50)),
                ('is_exchange_policy_available', models.BooleanField(default=True)),
                ('is_return_policy_available', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('product_stock', models.CharField(default='10', max_length=20)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, default=list, size=None)),
                ('mrp', models.DecimalField(decimal_places=3, default='0', max_digits=19)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'product_master',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Rolemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=55, null=True)),
                ('role_desc', models.CharField(blank=True, max_length=55, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_master',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoleMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.Rolemaster')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_mapping',
                'ordering': ('created_at',),
            },
        ),
    ]
