# Generated by Django 3.0.6 on 2025-06-20 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=55, null=True)),
                ('role_desc', models.CharField(blank=True, max_length=55, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_master',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoleMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.Rolemaster')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_mapping',
                'ordering': ('created_at',),
            },
        ),
    ]
