# Generated by Django 3.0.6 on 2025-06-23 10:06

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=55, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_be_deleted', models.BooleanField(default=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('return_days', models.CharField(default=0, max_length=50)),
                ('expected_delivery_days', models.CharField(default=0, max_length=50)),
                ('is_exchange_policy_available', models.BooleanField(default=True)),
                ('is_return_policy_available', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('product_stock', models.CharField(default='10', max_length=20)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'product_master',
                'ordering': ('created_at',),
            },
        ),
    ]
