# Generated by Django 3.0.6 on 2025-06-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_productmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='mrp',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=29),
        ),
    ]
