# Generated by Django 3.0.6 on 2025-06-25 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0003_productmaster_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumerid', models.CharField(blank=True, max_length=32, null=True)),
                ('completeddatetime', models.DateTimeField(null=True)),
                ('cancellationdone', models.BooleanField(default=False)),
                ('cancelled_by', models.CharField(blank=True, max_length=30, null=True)),
                ('cancellationdatetime', models.DateTimeField(null=True)),
                ('paymentdone', models.BooleanField(default=False)),
                ('order_status', models.CharField(default='inprogress', max_length=32)),
                ('wrapupsstatus', models.CharField(default='', max_length=32)),
                ('order_completed', models.BooleanField(default=False)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('cancellationreason', models.CharField(max_length=300, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productid', to='adminapp.Productmaster')),
            ],
            options={
                'db_table': 'order_details',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cartitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem_user_product', to='adminapp.Productmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_cart',
                'ordering': ('-created_at',),
            },
        ),
    ]
