# Generated by Django 3.0.6 on 2025-06-25 12:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_cartitems_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellableOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_delivery_fee', models.DecimalField(decimal_places=3, default='0', max_digits=19)),
                ('is_returned', models.BooleanField(default=False)),
                ('return_replace_actiondetails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('return_pickup_location', models.CharField(blank=True, max_length=250, null=True)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('return_quantity', models.IntegerField(default=0)),
                ('return_price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('return_tax_total', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('return_price_total', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('return_completed_time', models.DateTimeField(blank=True, null=True)),
                ('is_replacement', models.BooleanField(default=False)),
                ('replacement_pickup_location', models.CharField(blank=True, max_length=250, null=True)),
                ('replacement_reason', models.TextField(blank=True, null=True)),
                ('replacement_completed_time', models.DateTimeField(blank=True, null=True)),
                ('return_replace_quantity', models.IntegerField(default=0)),
                ('delivered_location', models.TextField(blank=True, null=True)),
                ('delivered_area', models.CharField(blank=True, max_length=30, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails_id', to='adminapp.OrderDetails')),
            ],
            options={
                'db_table': 'sellable_order_details',
                'ordering': ('created_at',),
            },
        ),
    ]
