# Generated by Django 4.2.23 on 2025-06-30 11:24

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_cartitems_id_alter_orderdetails_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=adminapp.models.product_image_upload_path),
        ),
    ]
