"""
Django settings for finance_management project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import json
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# #Set settings values from environment variables or env.json file
# print("yai")
# print(os.path)
# if os.path.isfile('env.json'):
env_path = os.path.join(BASE_DIR, 'env.json')

if os.path.isfile(env_path):
    with open(env_path) as f:
        
        data = json.load(f)
        try:
            APPLICATION_HOST = os.environ["APPLICATION_HOST"]
        except:
            APPLICATION_HOST = data['APPLICATION_HOST']
        try:
            db_name = os.environ["db_name"]
        except:
            db_name = data['db_name']

        try:
            db_password = os.environ["db_password"]
        except:
            db_password = data['db_password']

        try:
            db_user = os.environ["db_user"]
        except:
            db_user = data['db_user']

        try:
            db_host = os.environ["db_host"]
        except:
            db_host = data['db_host']

        try:
            db_port = os.environ["db_port"]
        except:
            db_port = data['db_port']

        try:
            logsdb_name = os.environ["logsdb_name"]
        except:
            logsdb_name = data['logsdb_name']

        try:
            logsdb_password = os.environ["logsdb_password"]
        except:
            logsdb_password = data['logsdb_password']

        try:
            logsdb_user = os.environ["logsdb_user"]
        except:
            logsdb_user = data['logsdb_user']

        try:
            logsdb_host = os.environ["logsdb_host"]
        except:
            logsdb_host = data['logsdb_host']

        try:
            logsdb_port = os.environ["logsdb_port"]
        except:
            logsdb_port = data['logsdb_port']

        try:
            JWT_VERIFY = os.environ["JWT_VERIFY"]
        except:
            JWT_VERIFY = data['JWT_VERIFY']

        try:
            JWT_VERIFY_EXPIRATION = os.environ["JWT_VERIFY_EXPIRATION"]
        except:
            JWT_VERIFY_EXPIRATION = data['JWT_VERIFY_EXPIRATION']

        try:
            JWT_EXPIRATION_TIME = os.environ["JWT_EXPIRATION_TIME"]
        except:
            JWT_EXPIRATION_TIME = data['JWT_EXPIRATION_TIME']

        try:
            JWT_AUTH_HEADER_PREFIX = os.environ["JWT_AUTH_HEADER_PREFIX"]
        except:
            JWT_AUTH_HEADER_PREFIX = data['JWT_AUTH_HEADER_PREFIX']

        try:
            JWT_ALGORITHM = os.environ["JWT_ALGORITHM"]
        except:
            JWT_ALGORITHM = data['JWT_ALGORITHM']

        try:
            JWT_PAYLOAD_HANDLER = os.environ["JWT_PAYLOAD_HANDLER"]
        except:
            JWT_PAYLOAD_HANDLER = data['JWT_PAYLOAD_HANDLER']
else:
    db_name = os.environ['DB_NAME']
    db_user = os.environ['DB_USERNAME']
    db_password = os.environ['DB_PASSWORD']
    db_host = os.environ['DB_HOSTNAME']
    db_port = os.environ['DB_PORT']

    logsdb_name = os.environ["logsdb_name"]
    logsdb_password = os.environ["logsdb_password"]
    logsdb_user = os.environ['logsdb_user']
    logsdb_host = os.environ['logsdb_host']
    logsdb_port = os.environ['logsdb_port']


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(718o-(ou%kvvivs-l2-_wk5@=pvdb!5@9lg!)g&cp!eg_v7bq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'adminapp',
    'users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'finance_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'finance_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db_name,
        'USER': db_user,
        'PASSWORD': db_password,
        'HOST': db_host,
        'PORT': db_port
    }

    # 'logs': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': logsdb_name,
    #     'USER': logsdb_user,
    #     'PASSWORD': logsdb_password,
    #     'HOST': logsdb_host,
    #     'PORT': logsdb_port
    # }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = False  # Not recommended — UTC is best for consistency

USE_L10N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
timezone = 'UTC'
